/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StcButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default "md"
         */
        "size": Size;
        /**
          * @default "primary"
         */
        "variant": Variant;
    }
    interface StcInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ""
         */
        "helperText": string;
        /**
          * @default ""
         */
        "label": string;
        /**
          * @default ""
         */
        "placeholder": string;
        /**
          * @default "default"
         */
        "state": InputState;
        /**
          * @default ""
         */
        "value": string;
    }
    interface StcModal {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default ""
         */
        "title": string;
    }
}
export interface StcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStcInputElement;
}
export interface StcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStcModalElement;
}
declare global {
    interface HTMLStcButtonElement extends Components.StcButton, HTMLStencilElement {
    }
    var HTMLStcButtonElement: {
        prototype: HTMLStcButtonElement;
        new (): HTMLStcButtonElement;
    };
    interface HTMLStcInputElementEventMap {
        "stc-input": { value: string };
    }
    interface HTMLStcInputElement extends Components.StcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStcInputElementEventMap>(type: K, listener: (this: HTMLStcInputElement, ev: StcInputCustomEvent<HTMLStcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStcInputElementEventMap>(type: K, listener: (this: HTMLStcInputElement, ev: StcInputCustomEvent<HTMLStcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStcInputElement: {
        prototype: HTMLStcInputElement;
        new (): HTMLStcInputElement;
    };
    interface HTMLStcModalElementEventMap {
        "stc-close": void;
    }
    interface HTMLStcModalElement extends Components.StcModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStcModalElementEventMap>(type: K, listener: (this: HTMLStcModalElement, ev: StcModalCustomEvent<HTMLStcModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStcModalElementEventMap>(type: K, listener: (this: HTMLStcModalElement, ev: StcModalCustomEvent<HTMLStcModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStcModalElement: {
        prototype: HTMLStcModalElement;
        new (): HTMLStcModalElement;
    };
    interface HTMLElementTagNameMap {
        "stc-button": HTMLStcButtonElement;
        "stc-input": HTMLStcInputElement;
        "stc-modal": HTMLStcModalElement;
    }
}
declare namespace LocalJSX {
    interface StcButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default "md"
         */
        "size"?: Size;
        /**
          * @default "primary"
         */
        "variant"?: Variant;
    }
    interface StcInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "helperText"?: string;
        /**
          * @default ""
         */
        "label"?: string;
        /**
          * Emits on each input
         */
        "onStc-input"?: (event: StcInputCustomEvent<{ value: string }>) => void;
        /**
          * @default ""
         */
        "placeholder"?: string;
        /**
          * @default "default"
         */
        "state"?: InputState;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface StcModal {
        "onStc-close"?: (event: StcModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default ""
         */
        "title"?: string;
    }
    interface IntrinsicElements {
        "stc-button": StcButton;
        "stc-input": StcInput;
        "stc-modal": StcModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stc-button": LocalJSX.StcButton & JSXBase.HTMLAttributes<HTMLStcButtonElement>;
            "stc-input": LocalJSX.StcInput & JSXBase.HTMLAttributes<HTMLStcInputElement>;
            "stc-modal": LocalJSX.StcModal & JSXBase.HTMLAttributes<HTMLStcModalElement>;
        }
    }
}
